# Generated by Django 4.1.7 on 2023-02-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('contact_person_name', models.CharField(max_length=50)),
                ('contact_person_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.supplier')),
            ],
        ),
    ]
